server:
    address: 0.0.0.0
    port: 8080

spring:
    datasource:
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        # 로컬
        jdbc-url: jdbc:log4jdbc:mysql://localhost:3306/shop?createDatabaseIfNotExist=false&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&useSSL=true
        # 외부
        # jdbc-url: jdbc:log4jdbc:mysql://119.193.0.189:3306/shop?createDatabaseIfNotExist=false&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&useSSL=true
        username: shopadmin
        password: 940208

# 로그 설정
logging:
    level:
        jdbc:
            sqlonly: info
            sqltiming: off
            resultsettable: info
            audit: off
            resultset: off
            connection: off